### ISSUE TITLE
有bug会崩溃

### ISSUE THREAD

**Issue by lijuncai** [MarkMjw/PullScrollView#10]
当不停的向下拉，头部会多出一块空白，在一直下拉到底，会崩溃，程序

**Comment by msdx** [comment]
我没有遇见此问题。。尝试了许多，也没出现错误。楼主如果没有后续的日志或问题描述，我觉得作者 @MarkMjw 可以将此issue关闭。即此问题可能已经被修复或者是由于其他原因导致。有进一步的证据或问题描述时再打开。
