### ISSUE TITLE
当控件内子控件定义onclick事件时，在子控件上滑不动

### ISSUE THREAD

**Issue by yangsainan** [MarkMjw/PullScrollView#11]
重写scrollview的时候onInterceptTouchEvent是不是还应该再处理下？

**Comment by yangsainan** [comment]
@Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {
            mTouchDownY = ev.getY();
            mCurrentTop = mInitTop = mHeader.getTop();
            mCurrentBottom = mInitBottom = mHeader.getBottom();
        }
        if(ev.getAction() == MotionEvent.ACTION_MOVE){
        	return true;
        }
        return super.onInterceptTouchEvent(ev);
    }
我加了一句之后，子控件的点击事件不太灵了，这是为什么？

**Comment by msdx** [comment]
@MarkMjw 
I'd tried to fix it at https://github.com/msdx/PullScrollView/commit/bb199d71a4414597357a499048721f77b8451883. After the commit had been merged, I think you can close this issue.

**Comment by MarkMjw** [comment]
@msdx thanks.
