### ISSUE TITLE
能否把对应的类抽出来发布？

### ISSUE THREAD

**Issue by msdx** [MarkMjw/PullScrollView#12]
能否把对应的类抽出来到一个module中并发布到maven或jcenter作为远程依赖？

**Comment by MarkMjw** [comment]
这个项目只能算一个Demo，而且写得不好，所以我觉得没有必要提maven仓库，感谢你的支持，希望能理解！

**Comment by msdx** [comment]
我刚给你发了邮件，没想到你现在正好在线。
这个项目简单精悍，不然也不会有近400的关注及近两百的fork了。而且使用这个项目的人不少，现在项目应该也处于较稳定的情况。不发布不影响别人对它的使用，但发布了可以更便于他人的使用。且发布到jcenter上也挺方便的，代码分离出来后，几分钟就可以搞定了。

**Comment by MarkMjw** [comment]
好，有空试试。
